### PR TITLE
resolves #951, create db backup cron job, update readme

### PR DESCRIPTION
**Pull request by cubann**
Cronjob that consists of two containers: postgres container connects via db service to DB and  create backupfiles, 2nd container aws-cli uploads backupfiles to aws s3 only after 1st container finishes creation of backup files

### CODE REVIEW

**Comment by cubann** [comment]
@OriHoch Please review
@atalyaalon  Removing backup files after a week, could be implemented via aws console, https://www.joe0.com/2017/05/24/amazon-s3-how-to-delete-files-older-than-x-days/

**Comment by OriHoch** [comment]
Looks great! thanks @cubann 

I would prefer to have a single custom image doing all this work, as the tools you are using are easy to install (just pg_dump and aws cli). This reduces image size, improves security and also could be managed as part of the anyway code repository.

Other then that, I would like to see the full anyway chart completed before merging, as the current anyway production environment here is not deployed yet.

**Comment by atalyaalon** [comment]
@cubann how should we manage the versions of previous days
what happens if in the bucket there are versions of previous days with the same file name? 
Are they overridden? 
Perhaps we can name the latest dumps with a prefix/suffix "latest" and the rest will contain date?
Meaning we need to change the prefix/suffix in the name of the latest dump in the bucket to yesterday's date?

Also regarding the port 5432 - I changed the exposed port to 9876 - see the [docker-compose.yml](https://github.com/hasadna/anyway/blob/dev/docker-compose.yml) since anyone with postgres on the computer can have issues when 5432 is exposed.
Not sure if you need to change it in the script - since the containerPort is the internal one?

Regarding the postgres image (postgres:9.6.17-alpine) - is it necessary? since we already have a db container (see our [docker-compose.yml](https://github.com/hasadna/anyway/blob/dev/docker-compose.yml)
So the cron only needs to execute the commands inside it, right? no need to a new container? Or did I miss anything?

Anyway, great work @cubann!
And great work of our @hasadna/anyway-devops team!

**Comment by atalyaalon** [comment]
Also - one more question - what's the best way to restrict access to the public dumps - so that only volunteers with a certain key can access the most recent public dump?
@cubann @ItamarLevin @OriHoch any suggestions?

**Comment by OriHoch** [comment]
container port could be removed because this image is not serving any DB

regarding the port of the DB, this is another reason the backups should be part of anyway code, that way it's clear which DB it connects to and everything is in one place.

regarding exposing the public DB dump - can be done using nginx with http authentication, the ingress supports http authentication, for example - https://github.com/hasadna/hasadna-k8s/blob/master/charts-external/avidcovider/templates/ingresses.yaml#L14

**Comment by atalyaalon** [comment]
Thanks @OriHoch 
@ItamarLevin @cubann what do you think? How should we proceed from here?

**Comment by cubann** [comment]
> @cubann how should we manage the versions of previous days
> what happens if in the bucket there are versions of previous days with the same file name?
> Are they overridden?
@cubann as fas as I know if versioning is enabled on this bucket they will be overridden, but you will have access to all of them. As I previously mentioned we can use bucket life cycle rules in order to delete all files older than 7 days. Here the link for example steps: https://www.joe0.com/2017/05/24/amazon-s3-how-to-delete-files-older-than-x-days/

**Comment by cubann** [comment]
> Looks great! thanks @cubann
> 
> I would prefer to have a single custom image doing all this work, as the tools you are using are easy to install (just pg_dump and aws cli). This reduces image size, improves security and also could be managed as part of the anyway code repository.
> 
> Other then that, I would like to see the full anyway chart completed before merging, as the current anyway production environment here is not deployed yet.

@OriHoch I have made two containers for "separation of concerns", but you are right if we would need only these two commands, creation of custom image could be better.
@OriHoch I am not sure that I understood   `full anyway chart completed before merging` and regarding custom docker image - do we have hasadna docker hub? how and where it should be created?

**Comment by OriHoch** [comment]
let's have a meeting about it, we can sync on Slack

**Comment by atalyaalon** [comment]
@OriHoch why is this committed? I thought we wanted to have the backups in anyway's environment?

**Comment by OriHoch** [comment]
yes, but I'll still use some of this code for the cronjob

**Pull request merged**
